---
- name: check if redis-sentinel is installed
  command: dpkg-query -W redis-sentinel
  register: dpkg_result
  failed_when: dpkg_result.rc > 1
  changed_when: no  # command doesn't change target's state

- name: redis sentinel installation
  apt: name=redis-sentinel state=latest update_cache=yes
  notify: restart sentinel

- name: enable redis-sentinel service
  systemd:
    name: redis-sentinel
    state: started
    enabled: yes

- name: redis sentinel initial config
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    owner: redis
    group: redis
    mode: '0640'
    backup: true
  notify: restart sentinel
  when: dpkg_result.rc == 1

- name: redis sentinel configuration
  template:
    src: sentinel_includes.conf.j2
    dest: /etc/redis/sentinel_includes.conf
    owner: redis
    group: redis
    mode: '0640'
    backup: true
  notify: restart sentinel
